### ISSUE TITLE
Unable to create HARE rpm using make command

### ISSUE THREAD

**Issue by TechWriter-Mayur** [Seagate/cortx-hare#1656]
Unable to create hare rpm using make command:

```
--> Checking hare_mp
--> Checking files with flake8
--> Checking files with mypy
hare_mp/store.py:21: error: Cannot find implementation or library stub for module named "cortx.utils.conf_store"
hare_mp/main.py:34: error: Cannot find implementation or library stub for module named "cortx.utils.product_features"
hare_mp/main.py:34: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
hare_mp/main.py:77: error: Module has no attribute "handlers"; maybe "Handler"?
Found 3 errors in 2 files (checked 8 source files)
make[2]: *** [mypy] Error 1
make[1]: *** [check-miniprov] Error 2
make: *** [build] Error 2

```

**Comment by knekrasov** [comment]
@TechWriter-Mayur I believe you didn't install cortx-py-utils.

**Comment by TechWriter-Mayur** [comment]
@knekrasov it is installed, I have run the following to install as suggested in the doc:
`sudo yum -y install yum-utils `

**Comment by knekrasov** [comment]
No, `yum-utils` and `cortx-py-utils` are different things. `cortx-py-utils` is an RPM built on the top of https://github.com/Seagate/cortx-utils/ repository. At Seagate Jenkins there are built RPMs that you can take and install.

In case the user doesn't have the access to Seagate RPMs, (s)he will have to build the RPM manually from the sources.

But the problem you're observing is caused by missing Python modules that are provided by cortx-py-utils, sorry.

**Comment by TechWriter-Mayur** [comment]
oh okay. Let me install the CORTX-utils. But, we need to add this in doc also if it is required.

**Comment by knekrasov** [comment]
Yes, good point. In fact, I already have a PR for that #1595 
It's time to merge it..

**Comment by TechWriter-Mayur** [comment]
The issue is fixed as per the provided instruction. Hence, closing this issue.
