### ISSUE TITLE
facter 3.14.8 or higher rpm is not available on CentOS 7

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1834]
CentOS 7 is the main platform for CORTX atm. Yet, Hare requires facter 3.14.8 or higher version, which is not available in the public rpm repos:

```
[seagate@sage-tier1-1 ~]$ hctl bootstrap --mkfs /home/users/project/SHARED/sage-update-20210916/sage-proto-cdf-4cl.yaml
2021-10-16 12:10:17: Generating cluster configuration...Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 2170, in <module>
    main()
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 216, in main
    enrich_cluster_desc(cluster_desc, opts.mock)
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 309, in enrich_cluster_desc
    ipaddr_key(node['data_iface']))
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 549, in get_facts
    validate_facter(hostname)
  File "/opt/seagate/cortx/hare/bin/../bin/cfgen", line 542, in validate_facter
    f'Unsupported facter version found at node {hostname}: {ver_str}. '
RuntimeError: Unsupported facter version found at node client-26: 2.4.1
. Please use 3.14.8 or higher.
```

The standard facter version on CentOS 7 is 2.4.1:

```
$ sudo yum list '*facter*'
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.xtom.de
 * centos-sclo-rh: de.mirrors.clouvider.net
 * centos-sclo-sclo: ftp.uni-bayreuth.de
 * epel: mirror.imt-systems.com
 * extras: de.mirrors.clouvider.net
 * updates: mirror.23m.com
Available Packages
facter.x86_64                         2.4.1-1.el7                    epel
```

**Comment by knekrasov** [comment]
@vaibhavparatwar some time ago we observed a bug in facter 2.x.x and it took quite much of efforts to debug. Here is the link to the investigation results: https://jts.seagate.com/browse/EOS-15307?focusedCommentId=1988577&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1988577

With facter 2.x.x, if the ethernet interfaces use labels, they will not be processed correctly while running cfgen. We don't know exactly at which facter version the bug was fixed, but we know for sure that versopm 3.14.8 doesn't have this bug.

Suggestions:
1. Plan sequence of testing with different `facter` versions to identify what is the actual minimal version that we need.
2. Investigate if `cfgen` can work around this problem if it sees an outdated facter tool.
3. Ship `facter` tool together with Hare RPM.
4. Implement our own subset of `facter` tool (we don't use that much, actually: I guess RAM size, CPU count and IP addresses are the only things we query from facter).
5. Don't do anything: in Kubernetes environment we don't rely on facter anyway. So once Kubernetes becomes the only deployment model, the issue will disappear automatically.

**Comment by andriytk** [comment]
> So once Kubernetes becomes the only deployment model, the issue will disappear automatically.

Kubernetes is not planned in EU R&D projects (SAGE, IO-SEA, etc.)

**Comment by andriytk** [comment]
I will close it, as the problem will be fixed on CentOS 8 by #1862.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Closing as its closed in github by reporter

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
