### ISSUE TITLE
Compile jq: error: Invalid numeric literal at EOF at line 1, column 12 (while parsing '192.168.60.4') at <top-level>, line 5:

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-hare#1924]
I am trying to start motr single node ( by adding transport_type: inet in CDF.yaml which was missing in the current sample file)

However, had encounter this issue :

![image](https://user-images.githubusercontent.com/77140436/147655642-f6a913b1-9f1c-4442-9b30-b226ad037170.png)

any idea ?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27225. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by mssawant** [comment]
thanks @kiwionly2, this is addressed by https://github.com/Seagate/cortx-hare/pull/1926

**Comment by cortx-admin** [comment]
> Mandar Sawant commented in Jira Server:

Review at https://github.com/Seagate/cortx-hare/pull/1926

**Comment by mssawant** [comment]
@kiwionly2, https://github.com/Seagate/cortx-hare/pull/1926 is merged, can you please reverify from your side and close the issue if working?

**Comment by cortx-admin** [comment]
> Mandar Sawant commented in Jira Server:

https://github.com/Seagate/cortx-hare/pull/1926 merged to main.

**Comment by kiwionly2** [comment]
see #1922

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
