### ISSUE TITLE
Broken link on cortx-hare rfc 10 document

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-hare#1936]
Hi,

While browser the [cortx-hare/rfc/10/readme.md ](https://github.com/Seagate/cortx-hare/blob/main/rfc/10/README.md), found that link for **3CFGEN** is broken.

Instead of 

`https://github.com/Seagate/cortx-hare/blob/main/rfc/10/rfc/3/README.md`

the correct one should be 

`https://github.com/Seagate/cortx-hare/blob/main/rfc/3/README.md`

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27290. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Merged.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
