### ISSUE TITLE
hare sudo make install fail 

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-hare#1943]
I am install a fresh copy of hare from git and try to build it by follow the documentation of hare.

Everything is working fin until the last step when I try to run `sudo make install`

here the error I get

![image](https://user-images.githubusercontent.com/77140436/148801529-4189d48e-2ad4-443d-9519-9d238788e799.png)

Any idea ?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27332. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by kiwionly2** [comment]
I need to manually remove the `/opt/seagate` directory, and now it work, is that something missing in the install script ?

**Comment by hessio** [comment]
HI @kiwionly2 I am not sure. Let me ask @knekrasov

**Comment by supriyachavan4398** [comment]
Hi @kiwionly2, 
do you use `make clean` before using the `make install` command?
Please run these commands one after the other.
 ```
 make uninstall 
 make clean
 make
 make install
 ```
 If you run these commands, this problem will not occur.

**Comment by cortx-admin** [comment]
> Supriya Chavan commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Supriya Chavan commented in Jira Server:

As it's a documentation error, We can improve there.

**Comment by cortx-admin** [comment]
> Supriya Chavan commented in Jira Server:

.
