### ISSUE TITLE
FDMI filter fid to be shown in hctl status

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1954]
Currently, the only way for a user to get FDMI filter fid configured in CDF is to look into `conf.xc` and try to parse it. This is very inconvenient. `conf.xc` is an internal low-level configuration file for motr and it is not supposed to be analysed by a cluster user.

Suggestion: show FDMI filters fids in the output of `hctl status --json` command or add an additional option (`--fdmi`?) to show them.

Relates to https://github.com/Seagate/cortx-rgw/pull/51.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27674. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

Improvement / refactor cc [~520513]

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

moving this to story Jira instead of Bug Jira . cc [~520513] [~520478]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
