### ISSUE TITLE
status of m0_client remains offline after rgw restart

### ISSUE THREAD

**Issue by rajeshdesh** [Seagate/cortx-hare#1957]
I was running 16MB-200Sessions-12KObjects s3bench from client on single node MGW. During this test I observed that I/O started failing. Then I restarted RGW with ../src/stop.sh and ../src/vstart.sh scripts. At this stage, `hctl status` started showing m0_client as offline. After this, I followed steps like
- stopped RGW again with ../src/stop.sh
- hctl shutdown, then 
- hctl bootstrap --mkfs singlenode.yaml
- ../src/vstart.sh
This brought back the m0_client online

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27773. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by vaibhavparatwar** [comment]
@rajeshdesh please verify this again and comment.

**Comment by rajeshdesh** [comment]
yes @vaibhavparatwar , not hitting this issue with latest builds of Cortx-RGW

**Comment by vaibhavparatwar** [comment]
Closing as per @rajeshdesh's verification.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
