### ISSUE TITLE
Compiling error of cortx-hare still persists

### ISSUE THREAD

**Issue by kevinxyliu** [Seagate/cortx-hare#2040]
Hi,

I submitted an [issue](https://github.com/Seagate/cortx-hare/issues/2036) last week reporting a gcc error when compiling cortx-hare from source. Thanks for the quick response - I apologize for not checking it immediately as I have been out of town since then.

I checked the new main branch today and it seems that the same issue was still there. Did anyone merge a new branch to the main these days, or maybe the issue comes from something else? Maybe you can point me to an old branch where cortx-hare was shown to be compiling properly?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29821. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by vaibhavparatwar** [comment]
@kevinxyliu can you please test on Centos 7.9 or 8 ? @hessio can you please help here?

**Comment by hessio** [comment]
Yes no problem I will test this out

**Comment by vaibhavparatwar** [comment]
Thanks @kevinxyliu . @hessio thanks for your attention. Issue is resolved now.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

REJECTED.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.
