### ISSUE TITLE
Sometimes disks are offline just after fresh bootstrap

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#2061]
```
$ hctl bootstrap --mkfs ~/singlenode.yaml 
2022-04-22 15:43:23: Generating cluster configuration... OK
2022-04-22 15:43:25: Starting Consul server on this node.......... OK
2022-04-22 15:43:33: Importing configuration into the KV store... OK
2022-04-22 15:43:34: Starting Consul on other nodes...Consul ready on all nodes
2022-04-22 15:43:34: Updating Consul configuration from the KV store... OK
2022-04-22 15:43:37: Waiting for the RC Leader to get elected...... OK
2022-04-22 15:43:42: Starting Motr (phase1, mkfs)... OK
2022-04-22 15:43:58: Starting Motr (phase1, m0d)... OK
2022-04-22 15:44:03: Starting Motr (phase2, mkfs)... OK
2022-04-22 15:44:49: Starting Motr (phase2, m0d)... OK
2022-04-22 15:45:47: Checking health of services... OK
$ hctl status -d
Bytecount:
    critical : 0
    damaged : 0
    degraded : 0
    healthy : 0
Data pool:
    # fid name
    0x6f00000000000001:0x6b 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x9f 'default': 'the pool' None None
Services:
    rocky83  (RC)
    [started]  hax                 0x7200000000000001:0xa          inet:tcp:192.168.180.165@22001
    [started]  confd               0x7200000000000001:0xd          inet:tcp:192.168.180.165@21002
    [started]  ioservice           0x7200000000000001:0x10         inet:tcp:192.168.180.165@21003
    [started]  ioservice           0x7200000000000001:0x1f         inet:tcp:192.168.180.165@21004
    [started]  ioservice           0x7200000000000001:0x2e         inet:tcp:192.168.180.165@21005
    [started]  ioservice           0x7200000000000001:0x3d         inet:tcp:192.168.180.165@21006
    [started]  ioservice           0x7200000000000001:0x4c         inet:tcp:192.168.180.165@21007
    [unknown]  m0_client_other     0x7200000000000001:0x5b         inet:tcp:192.168.180.165@22501
    [unknown]  m0_client_other     0x7200000000000001:0x5e         inet:tcp:192.168.180.165@22502
Devices:
    rocky83
    [online]  /dev/loop0
    [online]  /dev/loop1
    [online]  /dev/null
    [online]  /dev/loop2
    [online]  /dev/loop3
    [online]  /dev/null
    [offline]  /dev/loop4
    [offline]  /dev/loop5
    [offline]  /dev/null
    [online]  /dev/loop6
    [online]  /dev/loop7
    [online]  /dev/null
    [online]  /dev/loop8
    [online]  /dev/loop9
    [online]  /dev/null
```

Re-bootstrap may help it, but still - why they are offline?

Noticed on commit b46d6b4.

**Comment by andriytk** [comment]
@mssawant is this something known?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30982. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by mssawant** [comment]
@andriytk, please rebase with latest Hare main and try,
```
commit e405edf60fe49e90caa73346ae88f44c5394c25d
Author: Mandar Sawant <mandar.sawant@seagate.com>
Date:   Wed Apr 20 15:32:37 2022 -0600
```

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

user need to take latest hare repo as per above comments. So closing this ticket

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

,

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Vaibhav Prakash Paratwar commented in Jira Server:

As its not seen on latest repo, closing this. [~520414] please use latest hare commit as per Mandar's comments.

**Comment by andriytk** [comment]
@mssawant, have you root-cased it and fixed, or you just weren't able to reproduce it?

**Comment by mssawant** [comment]
@andriytk, yes. The problem was that we were reporting the process status as OFFLINE when asked for the current process status if Consul status was `passing` but process status was not `M0_CONF_HA_PROCESS_STARTED`  an reported ONLINE only after process transitioned to `M0_CONF_HA_PROCESS_STARTED`. But this was causing a race condition where this OFFLINE process state was updated in Consul and also reported the same to Motr after Process was STARTED causing devices to remain offline. We did see this in container deployment as well, where the devices remained offline post deployment.
Now we report the process status as UNKNOWN is consul services status is `passing` but process status is not M0_CONF_HA_PROCESS_STARTED.
