### ISSUE TITLE
Hare Architecture document is private

### ISSUE THREAD

**Issue by keithpine** [Seagate/cortx-hare#2158]
### Problem

The link in the README.md document to the Hare Architecture re-directs to a Seagate-private Confluence page. It looks like the document was once public, but now re-directs to a private one.

Offending link:
https://github.com/Seagate/cortx-hare/blob/bd943b6dd93e84f265dd34291fad7f94e8732c43/README.md?plain=1#L340

Clicking on that link re-directs you to a login page, if you're able to login, a page in the private CORTX space.

### Expected behavior

The document should be public and not require a login if it's linked from a public GitHub page.

### How to reproduce

Click on the link from while logged out of Seagate Confluence.

### Deployment information

N/A

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-34076. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

I tried to move it but it says I don't have the permissions to move this document

**Comment by hessio** [comment]
@mukul-seagate11 can you see if you have permissions to update this?

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
